### ISSUE TITLE
Issue with LAB promotion rules?

### ISSUE THREAD

**Issue by ltiao** [vdutor/SphericalHarmonics#6]
I encounter the following error. There should be a simple fix but I am not sufficiently familiar with LAB.

```
Traceback (most recent call last):
  [...]
  File "/home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/optimizers/scipy.py", line 95, in minimize
    return scipy.optimize.minimize(
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 681, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_lbfgsb_py.py", line 308, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 263, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 158, in __init__
    self._update_fun()
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/scipy/optimize/_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/optimizers/scipy.py", line 137, in _eval
    loss, grad = _tf_eval(tf.convert_to_tensor(x))
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/optimizers/scipy.py:121 _tf_eval  *
        loss, grads = _compute_loss_and_gradients(
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/optimizers/scipy.py:224 _compute_loss_and_gradients  *
        loss = loss_closure()
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/training_mixins.py:131 closure  *
        return training_loss(data)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/training_mixins.py:99 training_loss  *
        return self._training_loss(data)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/model.py:56 _training_loss  *
        return -(self.maximum_log_likelihood_objective(*args, **kwargs) + self.log_prior_density())
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/svgp.py:139 maximum_log_likelihood_objective  *
        return self.elbo(data)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/svgp.py:148 elbo  *
        f_mean, f_var = self.predict_f(X, full_cov=False, full_output_cov=False)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/GPflow/gpflow/models/svgp.py:161 predict_f  *
        mu, var = conditional(
    /home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/multipledispatch/dispatcher.py:278 __call__  *
        return func(*args, **kwargs)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/gpflow_decomposed/models/spherical_harmonics/base.py:109 conditional_spherical_harmonic_features  *
        Kmn = Kuf(inducing_features, kernel, Xnew)  # still a Tensor
    /home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/multipledispatch/dispatcher.py:278 __call__  *
        return func(*args, **kwargs)
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/gpflow_decomposed/models/spherical_harmonics/base.py:59 Kuf_spherical_harmonic_features  *
        return tf.transpose(inducing_features.spherical_harmonics(X))
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/SphericalHarmonics/src/spherical_harmonics/spherical_harmonics.py:75 __call__  *
        values = map(
    /home/tiao/Repositories/gp-orthogonal-sh-relu-experiments/src/SphericalHarmonics/src/spherical_harmonics/spherical_harmonics.py:150 __call__  *
        VXT = B.matmul(self.V, X, tr_b=True)  # [M, N]
    plum/function.py:537 plum.function.Function.__call__  **
        
    /home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/lab/util.py:198 wrapper
        args = plum.promote(*args[:promote_index]) + args[promote_index:]
    plum/function.py:537 plum.function.Function.__call__
        
    /home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plum/promotion.py:148 promote
        common_type = _promotion_rule.invoke(types[0], types[1])(types[0], types[1])
    plum/function.py:552 plum.function.Function.invoke.wrapped_method
        
    /home/tiao/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plum/promotion.py:107 _promotion_rule
        raise TypeError(f'No promotion rule for "{type1}" and "{type2}".')

    TypeError: No promotion rule for "numpy.ndarray" and "tensorflow.python.framework.ops.Tensor".
```

**Comment by ltiao** [comment]
The model is defined as follows:

```
kernel = ChordMatern(nu=5/2, dimension=n_features+1)
kernel.eigenvalues(max_degree=degree)
likelihood = Gaussian(variance=noise_variance)
inducing_features = SphericalHarmonicFeatures(dimension=n_features+1, degrees=degree)
model = SVGP_deprecated(
    kernel=kernel,
    likelihood=likelihood,
    inducing_variable=inducing_features,
    mean_function=None, whiten=whiten,
    num_data=n_train,
)
```
